dist: xenial
language: python
python:
  - "2.7"
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install -U -r python/requirements.txt
  - install_cmdstan

script:
  - cd python && python setup.py develop test
